name: Azure Python Web App CI/CD

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: AiAgentRag
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies (for validation only)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      # 👉 Deploy directly (zip/artifact juggling)
      - name: Zip and Deploy
        run: zip -r deploy.zip .
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip